version: "3.9"

services:
  api-gateway:
    build:
      context: ./backend/api-gateway
    env_file: ./backend/api-gateway/.env
    ports:
      - "5000:5000"
    networks:
      - app-network

  auth-service:
    build:
      context: ./backend/auth-service
    env_file: ./backend/auth-service/.env
    ports:
      - "5001:5001"
    depends_on:
      - api-gateway
    networks:
      - app-network

  content-service:
    build:
      context: ./backend/content-service
    env_file: ./backend/content-service/.env
    ports:
      - "5003:5003"
    depends_on:
      - auth-service
      - api-gateway
    networks:
      - app-network

  ai-service:
    build:
      context: ./backend/ai-service
    env_file: ./backend/ai-service/.env
    ports:
      - "5002:5002"
    depends_on:
      - auth-service
      - content-service
      - ai-llama3
    networks:
      - app-network

  ai-llama3:
    build:
      context: ./backend/ai-llama3
    container_name: ai-llama3
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - app-network


  frontend:
    build:
      context: ./frontend
    environment:
      - VITE_API_URL=http://api-gateway:5000/api
    ports:
      - "4173:4173"
    depends_on:
      - api-gateway
    networks:
      - app-network

volumes:
  ollama_data:

networks:
  app-network:
    driver: bridge
