version: "3.9"

services:
  api-gateway:
    build:
      context: ./backend/api-gateway
    volumes:
      - ./backend/api-gateway:/app
      - /app/node_modules
    env_file: ./.env
    command: npm run dev
    ports:
      - "5000:5000"
    networks:
      - app-network

  auth-service:
    build:
      context: ./backend/auth-service
    volumes:
      - ./backend/auth-service:/app
      - /app/node_modules
    env_file: ./.env
    command: npm run dev
    ports:
      - "5001:5001"
    depends_on:
      - api-gateway
    networks:
      - app-network

  content-service:
    build:
      context: ./backend/content-service
    volumes:
      - ./backend/content-service:/app
      - /app/node_modules
    env_file: ./.env
    command: npm run dev
    ports:
      - "5003:5003"
    depends_on:
      - auth-service
      - api-gateway
    networks:
      - app-network

  ai-service:
    build:
      context: ./backend/ai-service
    volumes:
      - ./backend/ai-service:/app
      - /app/node_modules
    env_file: ./.env
    command: npm run dev
    ports:
      - "5002:5002"
    depends_on:
      - auth-service
      - content-service
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5000/api
    command: npm run dev
    env_file: ./.env
    ports:
      - "5173:5173"
    depends_on:
      - api-gateway
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
